### ISSUE TITLE
add Footer 

### ISSUE THREAD

**Issue by yumemayu** [dev-protocol/onboarding-sponsor#13]
Can you please add this footer? I found this in the Docs
And please also insert link to Stakes.social 

<img width="397" alt="Screen Shot 2021-06-16 at 16 00 53" src="https://user-images.githubusercontent.com/33956553/122172875-2b444500-cebc-11eb-9d78-3073e671341b.png">

![Stakes](https://user-images.githubusercontent.com/33956553/122173105-63e41e80-cebc-11eb-8f08-ef21e6873c86.png)

**Comment by kazu80** [comment]
I added it like this.

![スクリーンショット 2021-06-16 18 16 09](https://user-images.githubusercontent.com/4590559/122194875-d0691880-ced0-11eb-9438-94f238c86582.png)
