### ISSUE TITLE
Add "Invitation request link"

### ISSUE THREAD

**Issue by yumemayu** [dev-protocol/onboarding-sponsor#14]
Please add this to the footer in a cute way!

Do you have eligible OSS projects? Please send us request here! 
https://stakes.social/invite/github

**Comment by kazu80** [comment]
I added it like this. cute was hard work 😅

![スクリーンショット 2021-06-16 18 16 09](https://user-images.githubusercontent.com/4590559/122192839-f8f01300-cece-11eb-9678-135c15ceb89f.png)

**Comment by yumemayu** [comment]
Thanks!
