### ISSUE TITLE
Expected list component

### ISSUE THREAD

**Issue by aggre** [dev-protocol/onboarding-sponsor#4]
- The list should be starts at 1 and increments by 1 like `ol` element.
- The list should be sorted in descending order from the one with the most stars.
- The list should also include the name of the repository owner. (e.g. vuejs/vue-next)

![image](https://user-images.githubusercontent.com/1970283/122148756-fae9b000-ce95-11eb-933e-79fc26c4bd99.png)

**Comment by kazu80** [comment]
@aggre 

> The list should also include the name of the repository owner. (e.g. vuejs/vue-next)

```
173.   vuejs/vue-next ↗.       3.9k stars
```

Should I change it as above?

**Comment by aggre** [comment]
> Should I change it as above?

@kazu80 That's right!

**Comment by kazu80** [comment]
I did & marge
https://github.com/dev-protocol/onboarding-sponsor/pull/6

**Comment by aggre** [comment]
Thanks, great PR!
