### ISSUE TITLE
Wallet address

### ISSUE THREAD

**Issue by aggre** [dev-protocol/onboarding-sponsor#5]
The donation destination wallet address should be the following address.

```
0x4528e1D848A38AD3662EA11A1669B4831258252E
```

**Comment by aggre** [comment]
Sorry, I'll create a new Gnosis-safe, and this address will replace that address.

**Comment by aggre** [comment]
I edited, and the correct address is `0x4528e1D848A38AD3662EA11A1669B4831258252E`

**Comment by kazu80** [comment]
Should I change QRcode , œœ, Ethscan link ??

**Comment by kazu80** [comment]
Is it like this ?
![スクリーンショット 2021-06-16 13 15 37](https://user-images.githubusercontent.com/4590559/122156941-f7115a00-cea4-11eb-8881-017a6d88c177.png)

**Comment by aggre** [comment]
@kazu80 That's right!

**Comment by kazu80** [comment]
@aggre 
I did & marge
https://github.com/dev-protocol/onboarding-sponsor/pull/11/files

**Comment by aggre** [comment]
Cooool!
![](https://media1.tenor.com/images/9830067b16a69eb2dec00ee8aa5a6840/tenor.gif?itemid=17858243)
